services:
  - type: web
    name: astarr-music
    env: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

      - key: API_ID
        value: "37167023"

      - key: API_HASH
        value: "06879a10307f6e6db8114b911295a6ae"

      - key: API_KEY
        value: ""

      - key: BOT_TOKEN
        value: "8511575655:AAFp6vSTokoh5Ou6GVxrd6XH90-C53Gvve4"

      - key: MONGO_DB_URI
        value: "mongodb+srv://sikander025tg_db_user:A0Ksjm2i4r4znwy2@cluster0.xuelgmt.mongodb.net/?appName=Cluster0"

      - key: OWNER_ID
        value: "8785619142"

      - key: OWNER_USERNAME
        value: "SIKANDER_025"

      - key: BOT_USERNAME
        value: "AstarrMusicBot"

      - key: UPSTREAM_REPO
        value: "https://github.com/sikander025/AstarrMusic1"

      - key: STRING_SESSION
        value: "AgI3H68ABpCm_mFRt8VBUQpDIJdL00MEfjf02qU33r0Xzhpv1fjG2kmPF22OV61K_qHK4m15VCCsrjA662SFe9DsoRFRx2b_Mxqd13NlfwS7dUgQhVarGlO-vkCHy0yUTdFYm8D4jGMphvdE3W8Mt-7F2LP7kztuIKVjDRH9Fob8lbKTnnLaZpWhpiG5jM9Rr6Rl1Ss0ZvR_cFjCV30r6pLCBLafVt-7rwQ23JHClgDLp15VM1rY1HzcuguJC6kUj7Dm9fvJ9h8QAEK8q80IrjgqiRz02B8oHw8u-LR2SIOQpk5Oc2SXQ3KOmTTEuJ1CORKl0ySbpS1rTT0P2kvdWVvki81jzAAAAAILqejGAA"

      - key: LOG_GROUP_ID
        value: "-1003977469179"

      - key: SUPPORT_GROUP
        value: "https://t.me/AstarrMusicSupport"

      - key: SUPPORT_CHANNEL
        value: "https://t.me/AstarrMusicChannel"
